// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AutoSign
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinCustom uIItemCustom = this.UINewtabInternetExplorWindow.UIItemCustom;
            HtmlInputButton uI百度一下Button = this.UI百度一下你就知道InternetExplWindow.UI百度一下你就知道Document.UI百度一下Button;
            HtmlHyperlink uIDocumentationHyperlink = this.UINewtabInternetExplorWindow.UIWebPagetestWebsitePeDocument.UINavCustom.UIDocumentationHyperlink;
            WinCustom uIItemCustom1 = this.UINewtabInternetExplorWindow.UIItemCustom1;
            HtmlEdit uIWDEdit = this.UINewtabInternetExplorWindow.UI百度一下你就知道Document.UIWDEdit;
            #endregion

            // Last mouse action was not recorded.

            // Type 'w' in custom control
            Keyboard.SendKeys(uIItemCustom, this.RecordedMethod1Params.UIItemCustomSendKeys, ModifierKeys.None);

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(278, 39));

            // Type 'w' in custom control
            Keyboard.SendKeys(uIItemCustom, this.RecordedMethod1Params.UIItemCustomSendKeys1, ModifierKeys.None);

            // Type '{RShiftKey}w{Back}' in custom control
            Keyboard.SendKeys(uIItemCustom, this.RecordedMethod1Params.UIItemCustomSendKeys2, ModifierKeys.None);

            // Type '{RShiftKey}w.baidu.com{Enter}' in custom control
            Keyboard.SendKeys(uIItemCustom, this.RecordedMethod1Params.UIItemCustomSendKeys3, ModifierKeys.None);

            // Windows Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Click '百度一下' button
            Mouse.Click(uI百度一下Button, new Point(45, 31));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(288, 39));

            // Type 'www.webpagetest.org{Enter}' in custom control
            Keyboard.SendKeys(uIItemCustom, this.RecordedMethod1Params.UIItemCustomSendKeys4, ModifierKeys.None);

            // Click 'Documentation' link
            Mouse.Click(uIDocumentationHyperlink, new Point(115, 10));

            // Click custom control
            Mouse.Click(uIItemCustom1, new Point(230, -142));

            // Type '' in 'wd' text box
            uIWDEdit.Text = this.RecordedMethod1Params.UIWDEditText;
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        
        public UI百度一下你就知道InternetExplWindow UI百度一下你就知道InternetExplWindow
        {
            get
            {
                if ((this.mUI百度一下你就知道InternetExplWindow == null))
                {
                    this.mUI百度一下你就知道InternetExplWindow = new UI百度一下你就知道InternetExplWindow();
                }
                return this.mUI百度一下你就知道InternetExplWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        
        private UI百度一下你就知道InternetExplWindow mUI百度一下你就知道InternetExplWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'w' in custom control
        /// </summary>
        public string UIItemCustomSendKeys = "w";
        
        /// <summary>
        /// Type 'w' in custom control
        /// </summary>
        public string UIItemCustomSendKeys1 = "w";
        
        /// <summary>
        /// Type '{RShiftKey}w{Back}' in custom control
        /// </summary>
        public string UIItemCustomSendKeys2 = "{RShiftKey}w{Back}";
        
        /// <summary>
        /// Type '{RShiftKey}w.baidu.com{Enter}' in custom control
        /// </summary>
        public string UIItemCustomSendKeys3 = "{RShiftKey}w.baidu.com{Enter}";
        
        /// <summary>
        /// Type 'www.webpagetest.org{Enter}' in custom control
        /// </summary>
        public string UIItemCustomSendKeys4 = "www.webpagetest.org{Enter}";
        
        /// <summary>
        /// Type '' in 'wd' text box
        /// </summary>
        public string UIWDEditText = "";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("New tab - Internet Explorer");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIWebPagetestWebsitePeDocument UIWebPagetestWebsitePeDocument
        {
            get
            {
                if ((this.mUIWebPagetestWebsitePeDocument == null))
                {
                    this.mUIWebPagetestWebsitePeDocument = new UIWebPagetestWebsitePeDocument(this);
                }
                return this.mUIWebPagetestWebsitePeDocument;
            }
        }
        
        public WinCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.WindowTitles.Add("This page can’t be displayed - Internet Explorer");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UI百度一下你就知道Document UI百度一下你就知道Document
        {
            get
            {
                if ((this.mUI百度一下你就知道Document == null))
                {
                    this.mUI百度一下你就知道Document = new UI百度一下你就知道Document(this);
                }
                return this.mUI百度一下你就知道Document;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        
        private UIWebPagetestWebsitePeDocument mUIWebPagetestWebsitePeDocument;
        
        private WinCustom mUIItemCustom1;
        
        private UI百度一下你就知道Document mUI百度一下你就知道Document;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIWebPagetestWebsitePeDocument : HtmlDocument
    {
        
        public UIWebPagetestWebsitePeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "WebPagetest - Website Performance and Optimization Test";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.webpagetest.org/";
            this.WindowTitles.Add("WebPagetest - Website Performance and Optimization Test - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public UINavCustom UINavCustom
        {
            get
            {
                if ((this.mUINavCustom == null))
                {
                    this.mUINavCustom = new UINavCustom(this);
                }
                return this.mUINavCustom;
            }
        }
        #endregion
        
        #region Fields
        private UINavCustom mUINavCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UINavCustom : HtmlCustom
    {
        
        public UINavCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "nav";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "UL";
            this.FilterProperties["Class"] = "cufon-dincond_black";
            this.FilterProperties["ControlDefinition"] = "class=\"cufon-dincond_black\" id=\"nav\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("WebPagetest - Website Performance and Optimization Test - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDocumentationHyperlink
        {
            get
            {
                if ((this.mUIDocumentationHyperlink == null))
                {
                    this.mUIDocumentationHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDocumentationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDocumentationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDocumentationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUIDocumentationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Documentation";
                    this.mUIDocumentationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/a/webpagetest.org/docs/";
                    this.mUIDocumentationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Documentation (opens in a new tab)";
                    this.mUIDocumentationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://sites.google.com/a/webpagetest.org/docs/";
                    this.mUIDocumentationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDocumentationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Documentation (opens in a new tab";
                    this.mUIDocumentationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIDocumentationHyperlink.WindowTitles.Add("WebPagetest - Website Performance and Optimization Test - Internet Explorer");
                    #endregion
                }
                return this.mUIDocumentationHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDocumentationHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UI百度一下你就知道Document : HtmlDocument
    {
        
        public UI百度一下你就知道Document(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "百度一下，你就知道";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.baidu.com/";
            this.WindowTitles.Add("百度一下，你就知道 - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIWDEdit
        {
            get
            {
                if ((this.mUIWDEdit == null))
                {
                    this.mUIWDEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIWDEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "kw";
                    this.mUIWDEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "wd";
                    this.mUIWDEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIWDEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIWDEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIWDEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "s_ipt";
                    this.mUIWDEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"wd\" class=\"s_ipt\" id=\"kw\" maxlengt";
                    this.mUIWDEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUIWDEdit.WindowTitles.Add("百度一下，你就知道 - Internet Explorer");
                    #endregion
                }
                return this.mUIWDEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIWDEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UI百度一下你就知道InternetExplWindow : BrowserWindow
    {
        
        public UI百度一下你就知道InternetExplWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "百度一下，你就知道 - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("百度一下，你就知道 - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UI百度一下你就知道Document1 UI百度一下你就知道Document
        {
            get
            {
                if ((this.mUI百度一下你就知道Document == null))
                {
                    this.mUI百度一下你就知道Document = new UI百度一下你就知道Document1(this);
                }
                return this.mUI百度一下你就知道Document;
            }
        }
        #endregion
        
        #region Fields
        private UI百度一下你就知道Document1 mUI百度一下你就知道Document;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UI百度一下你就知道Document1 : HtmlDocument
    {
        
        public UI百度一下你就知道Document1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "百度一下，你就知道";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.baidu.com/";
            this.WindowTitles.Add("百度一下，你就知道 - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UI百度一下Button
        {
            get
            {
                if ((this.mUI百度一下Button == null))
                {
                    this.mUI百度一下Button = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUI百度一下Button.SearchProperties[HtmlButton.PropertyNames.Id] = "su";
                    this.mUI百度一下Button.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUI百度一下Button.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "百度一下";
                    this.mUI百度一下Button.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUI百度一下Button.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUI百度一下Button.FilterProperties[HtmlButton.PropertyNames.Class] = "bg s_btn btnhover";
                    this.mUI百度一下Button.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"bg s_btn btnhover\" id=\"su\" type=\"";
                    this.mUI百度一下Button.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "9";
                    this.mUI百度一下Button.WindowTitles.Add("百度一下，你就知道 - Internet Explorer");
                    #endregion
                }
                return this.mUI百度一下Button;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUI百度一下Button;
        #endregion
    }
}
